/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright 2026 amigazen project
 */

/*
  mkdesc.c

  Build-time host tool that emits the IFF DTYP descriptor binary for
  dr2d.datatype.  Run by the smakefile; produces the file the user
  installs to DEVS:DataTypes/DR2D.

  Why this exists
  ---------------
  The traditional way to ship a datatype descriptor is a hand-rolled
  .asm with `dc.b "FORM"...` assembled by vasm with `-Fbin` to drop a
  raw IFF FORM file.  SAS/C's bundled `asm` tool can produce neither
  raw-binary output nor binary includes, so we generate the same byte
  stream from C and write it through dos.library/Write instead.

  Class datatype vs. hook datatype
  --------------------------------
  dr2d.datatype is a full BOOPSI subclass of drawing.datatype, NOT a
  recognition hook.  DR2D files are canonical IFF (FORM DR2D), so the
  descriptor sets dth_Flags = DTF_IFF and dth_ID = "DR2D":
  datatypes.library then recognises matching files purely from their
  IFF FORM type and loads the class lazily by base name ("dr2d" ->
  CLASSES:datatypes/dr2d.datatype).  Consequently this descriptor
  carries NO DTCD chunk - there is no embedded recognition hook and no
  embedded class code.

  Output layout:

    "FORM" <length:long>
       "DTYP"
       "NAME" <len:long> <name-string>                 [even-padded]
       "DTHD" <len:long> <DataTypeHeader-shaped block>  [even-padded]
       "FVER" <len:long> <version-string>               [even-padded]

  All chunks are even-padded per IFF rules; the outer FORM length spans
  everything after itself.

  Usage:
    mkdesc <outputfile>

  Exits 0 on success, 10 (RETURN_ERROR) on any I/O or memory failure.
  Errors go to stderr so smake notices.

  We deliberately avoid iffparse.library so the build needs no extra
  libraries; the produced FORM/chunk layout is canonical IFF and any
  conformant parser - including datatypes.library's own - reads it.
*/

#include <exec/types.h>
#include <exec/memory.h>
#include <dos/dos.h>
#include <datatypes/datatypes.h>
#include <proto/exec.h>
#include <proto/dos.h>

#include <string.h>
#include <stdio.h>

#include "dr2d_rev.h"

/* Tag IDs as big-endian longwords.  The NDK already defines names like
 * ID_FORM, so these private names avoid SAS/C preprocessor redefinition
 * warnings while keeping the generated bytes explicit. */
#define DR2D_ID_FORM 0x464F524DUL   /* 'FORM' */
#define DR2D_ID_DTYP 0x44545950UL   /* 'DTYP' */
#define DR2D_ID_NAME 0x4E414D45UL   /* 'NAME' */
#define DR2D_ID_DTHD 0x44544844UL   /* 'DTHD' */
#define DR2D_ID_FVER 0x46564552UL   /* 'FVER' */

/* User-visible name, lookup base name and filename match pattern. */
static const char dt_name[]     = "DR2D";        /* DEVS:DataTypes/DR2D   */
static const char dt_basename[] = "dr2d";        /* -> dr2d.datatype      */
static const char dt_pattern[]  = "#?.dr2d";     /* fallback name match   */

/* IFF group and type ids - four ASCII chars each, no NUL. */
#define GROUP_ID "pict"   /* GID_PICTURE                            */
#define TYPE_ID  "DR2D"   /* IFF FORM type, exactly four characters */

/* DTF_IFF: datatypes.library matches dth_ID against the file's IFF
 * FORM type, so no comparison mask is required. */
#define DTH_FLAGS    0x0002  /* DTF_IFF      */
#define DTH_MASKLEN  0
#define DTH_PAD      0
#define DTH_PRI      0       /* FORM DR2D is unique; no tie-break needed */

/* --------------------------------------------------------------- */

static void put_be32(UBYTE *p, ULONG v)
{
	p[0] = (UBYTE)((v>>24) & 0xff);
	p[1] = (UBYTE)((v>>16) & 0xff);
	p[2] = (UBYTE)((v>> 8) & 0xff);
	p[3] = (UBYTE)( v      & 0xff);
}

static void put_be16(UBYTE *p, UWORD v)
{
	p[0] = (UBYTE)((v>>8) & 0xff);
	p[1] = (UBYTE)( v     & 0xff);
}

/* Append `len` bytes from src to dst[off..]; returns the new offset. */
static LONG append(UBYTE *dst, LONG off, const void *src, LONG len)
{
	memcpy(dst + off, src, (size_t)len);
	return off + len;
}

/* Append a chunk header (id, len); returns offset of first payload byte. */
static LONG begin_chunk(UBYTE *dst, LONG off, ULONG id, LONG len)
{
	put_be32(dst + off, id);
	put_be32(dst + off + 4, (ULONG)len);
	return off + 8;
}

/* Pad to even alignment, writing one zero byte if needed. */
static LONG even_pad(UBYTE *dst, LONG off)
{
	if(off & 1) dst[off++] = 0;
	return off;
}

int main(int argc, char *argv[])
{
	const char *outpath;
	UBYTE *out = NULL;
	LONG cap, off;
	LONG form_payload_start;
	LONG form_payload_end;
	LONG dthd_payload_start;
	LONG name_off, basename_off, pattern_off, mask_off;
	LONG name_len;
	LONG dthd_len;
	LONG fver_payload;
	BPTR fh;
	LONG nwritten;
	int rc = RETURN_OK;
	static const char fver_str[] = VERSTAG " by amigazen project";

	if(argc != 2)
	{
		fprintf(stderr, "usage: mkdesc <outputfile>\n");
		return RETURN_ERROR;
	}
	outpath = argv[1];

	/* Header + DTHD with strings + FVER is well under 1 KB; 4 KB is
	 * comfortably generous. */
	cap = 4096L;
	out = (UBYTE *)AllocVec(cap, MEMF_PUBLIC|MEMF_CLEAR);
	if(!out)
	{
		fprintf(stderr, "mkdesc: out of memory\n");
		return RETURN_ERROR;
	}

	/* Outer FORM header.  Patch the length once we know it. */
	off = begin_chunk(out, 0, DR2D_ID_FORM, 0);
	form_payload_start = off;

	/* DTYP type id (no length, just the four-byte form type). */
	put_be32(out + off, DR2D_ID_DTYP);
	off += 4;

	/* NAME chunk. */
	name_len = (LONG)sizeof(dt_name);    /* includes NUL */
	off = begin_chunk(out, off, DR2D_ID_NAME, name_len);
	off = append(out, off, dt_name, name_len);
	off = even_pad(out, off);

	/* DTHD chunk.  Build payload incrementally, fixing the string
	 * offset fields once we know where the strings live. */
	off = begin_chunk(out, off, DR2D_ID_DTHD, 0);   /* len patched below */
	dthd_payload_start = off;

	/* DataTypeHeader fixed part, written with placeholder offsets that
	 * we patch after the trailing string blob is appended. */
	put_be32(out + off,    0); off += 4;       /* dth_Name        */
	put_be32(out + off,    0); off += 4;       /* dth_BaseName    */
	put_be32(out + off,    0); off += 4;       /* dth_Pattern     */
	put_be32(out + off,    0); off += 4;       /* dth_Mask        */
	memcpy(out + off, GROUP_ID, 4); off += 4;  /* dth_GroupID     */
	memcpy(out + off, TYPE_ID , 4); off += 4;  /* dth_ID          */
	put_be16(out + off, DTH_MASKLEN); off += 2;
	put_be16(out + off, DTH_PAD);     off += 2;
	put_be16(out + off, DTH_FLAGS);   off += 2;
	put_be16(out + off, DTH_PRI);     off += 2;

	/* String blob: Name, BaseName, Pattern.  Each NUL-terminated;
	 * offsets are recorded relative to dthd_payload_start so the
	 * datatypes.library can rebase them after RAM load. */
	name_off = off - dthd_payload_start;
	off = append(out, off, dt_name, (LONG)sizeof(dt_name));
	basename_off = off - dthd_payload_start;
	off = append(out, off, dt_basename, (LONG)sizeof(dt_basename));
	pattern_off = off - dthd_payload_start;
	off = append(out, off, dt_pattern, (LONG)sizeof(dt_pattern));
	mask_off = name_off;   /* dummy - DTF_IFF needs no comparison mask */

	/* Patch the four offset fields. */
	put_be32(out + dthd_payload_start +  0, (ULONG)name_off);
	put_be32(out + dthd_payload_start +  4, (ULONG)basename_off);
	put_be32(out + dthd_payload_start +  8, (ULONG)pattern_off);
	put_be32(out + dthd_payload_start + 12, (ULONG)mask_off);

	/* Patch the DTHD chunk length. */
	dthd_len = off - dthd_payload_start;
	put_be32(out + dthd_payload_start - 4, (ULONG)dthd_len);
	off = even_pad(out, off);

	/* FVER chunk - version-tag + by-line, NUL terminated. */
	fver_payload = (LONG)sizeof(fver_str);
	off = begin_chunk(out, off, DR2D_ID_FVER, fver_payload);
	off = append(out, off, fver_str, fver_payload);
	off = even_pad(out, off);

	/* Patch outer FORM length (everything after the 8-byte FORM hdr). */
	form_payload_end = off;
	put_be32(out + 4, (ULONG)(form_payload_end - form_payload_start));

	/* Write the descriptor binary. */
	fh = Open((STRPTR)outpath, MODE_NEWFILE);
	if(!fh)
	{
		fprintf(stderr, "mkdesc: cannot create '%s'\n", outpath);
		rc = RETURN_ERROR;
		goto done;
	}
	nwritten = Write(fh, out, form_payload_end);
	Close(fh);
	if(nwritten != form_payload_end)
	{
		fprintf(stderr, "mkdesc: short write on '%s' (%ld of %ld)\n",
		        outpath, nwritten, form_payload_end);
		rc = RETURN_ERROR;
	}

done:
	if(out) FreeVec(out);
	return rc;
}
